#!/usr/bin/env bash

# script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line 

counter=1 # assign the variable counter the value of 1
while [ $counter -le 10 ] # checks if counter variable is <= 10
do
    echo "Best School" # display Best School
    if [ $counter -eq 9 ] # for the 9th iteration
    then
        echo "Hi" # display Hi
    fi
    ((counter++)) # increment counter by 1
done # end the loop



